# Generated by Django 5.2.15 on 2026-06-17 11:32

import apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(default=apps.transactions.models.generate_receipt_number, editable=False, max_length=32, unique=True),
        ),
    ]
