# Generated by Django 5.2.15 on 2026-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
